

package view;

import java.sql.Connection;

import javax.swing.JOptionPane;

import util.TeacherAccess;
import util.jdutil;

import model.View_Teacher;

/**
 *
 * @author  __USER__
 */
public class changepassword extends javax.swing.JInternalFrame {
	View_Teacher teacher;

	/** Creates new form changepassword */
	public changepassword() {
		initComponents();
	}

	public changepassword(View_Teacher teacher) {
		super();
		this.teacher = teacher;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		label1 = new java.awt.Label();
		label2 = new java.awt.Label();
		label3 = new java.awt.Label();
		button1 = new java.awt.Button();
		button2 = new java.awt.Button();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jPasswordField3 = new javax.swing.JPasswordField();

		label1.setText("\u539f\u5bc6\u7801");

		label2.setText("\u65b0\u5bc6\u7801");

		label3.setText("\u91cd\u590d\u5bc6\u7801");

		button1.setLabel("\u786e\u5b9a");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					button1ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		button2.setLabel("\u53d6\u6d88");
		button2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(79, 79,
																		79)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						label1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						label2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						label3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(98, 98,
																		98)
																.addComponent(
																		button1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(111,
																		111,
																		111)
																.addComponent(
																		button2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(24, 24,
																		24)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jPasswordField1,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						159,
																						Short.MAX_VALUE)
																				.addComponent(
																						jPasswordField2)
																				.addComponent(
																						jPasswordField3))))
								.addContainerGap(105, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(76, 76, 76)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														label1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jPasswordField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(16, 16, 16)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														label2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jPasswordField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														label3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jPasswordField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										44, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														button1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														button2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(40, 40, 40)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void button2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void button1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
		// TODO add your handling code here:
		String oldpas = new String(jPasswordField1.getPassword());
		String newpas = new String(jPasswordField2.getPassword());
		String secpas = new String(jPasswordField3.getPassword()); 
		if (oldpas.equals("")) {
			JOptionPane.showMessageDialog(this, "原密码不能为空", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField1.requestFocus();
			return;
		}
		if (newpas.equals("")) {
			JOptionPane.showMessageDialog(this, "新密码不能为空", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField2.requestFocus();
			return;
		}
		if (secpas.equals("")) {
			JOptionPane.showMessageDialog(this, "确认密码不能为空", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField3.requestFocus();
			return;
		}
		if (!newpas.equals(secpas)) {
			JOptionPane.showMessageDialog(this, "新密码与确认密码不相同，请重新输入", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField3.requestFocus();
			jPasswordField3.selectAll();
			return;
		}
		Connection connection=null;
		try {
			connection=jdutil.getCon();
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
		if(oldpas.equals(teacher.getT_password())) {
			teacher.setT_password(newpas);
			int re=TeacherAccess.changepassword(connection, teacher);
			if (re>0) {				
				JOptionPane.showMessageDialog(this, "您已成功修改密码");
			}else JOptionPane.showMessageDialog(this, "修改密码失败，请联系管理员");
		}else 
		{
			JOptionPane.showMessageDialog(this, "原密码错误，请重试");
			jPasswordField1.requestFocus();
			jPasswordField1.selectAll();
		}
		
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button button1;
	private java.awt.Button button2;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JPasswordField jPasswordField3;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private java.awt.Label label3;
	// End of variables declaration//GEN-END:variables

}