/*
 * throw_JIF.java
 *
 * Created on __DATE__, __TIME__
 */

package zzt.view;

import global.dao.Fileselection;
import global.dao.Majoraccess;
import global.model.Major;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import zxx.dao.PrintObjectExcel;

/**
 *
 * @author  __USER__
 */
public class throw_JIF extends javax.swing.JInternalFrame {

	/** Creates new form throw_JIF */
	public throw_JIF() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();

		jButton1.setText("\u5bfc\u51fa\u9519\u8bef\u5230excel\u8868\u4e2d");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(117, 117, 117)
						.addComponent(jButton1)
						.addContainerGap(133, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(496, Short.MAX_VALUE)
						.addComponent(jButton1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 45,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		
		// TODO add your handling code here:
				// TODO add your handling code here:
				//调用导出方法把文件的路径存放在tabletwo变量里
				File Filename = Fileselection.exportselect();
				File filenametow = new File(Filename + ".xls");
				String filetable = filenametow.toString();
				//				 System.out.println(Filename+".xls");
				String o_id = null;
				//实例化部门列表，把部门信息存放在calist变量中
				List<Major> caList = Majoraccess.getMajor(o_id);
				List<Major> list = new ArrayList<Major>();
				//设置excel表头信息
				String[] header = { "错误信息" };
				//				 File Filename =new File() ;
				//				 System.out.println(Filename);
				//				
				JFileChooser fDialog = new JFileChooser();
				if (Filename == null) {
					//					 System.out.println("文件名为null");
					return;
				}
				//怎么拿到导出之后的文件名
				if (filenametow.exists()) {
					System.out.println(filenametow.exists());
					int overwriteSelect = JOptionPane.showConfirmDialog(this,
							"<html><font size=3>文件" + filenametow.getName()
									+ "已存在，是否覆盖?</font><html>", "是否覆盖?",
							JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
					System.out.println(overwriteSelect);
					if (overwriteSelect == JOptionPane.YES_OPTION) {

						List<String> aList = PrintObjectExcel.printExcel(caList,
								filetable, header);
						if (aList.size() == 0) {
							JOptionPane.showMessageDialog(this, "导出成功", "提示信息",
									JOptionPane.INFORMATION_MESSAGE);
						} else {
							String str = "";
							for (String item : aList) {
								str += item + "\n";
							}
							JOptionPane.showMessageDialog(this, str, "错误信息",
									JOptionPane.ERROR_MESSAGE);
						}
					} else {
						return;
					}
				}
				List<String> aList = PrintObjectExcel.printExcel(caList, filetable,
						header);
				if (aList.size() == 0) {
					JOptionPane.showMessageDialog(this, "导出成功", "提示信息",
							JOptionPane.INFORMATION_MESSAGE);
				} else {
					String str = "";
					for (String item : aList) {
						str += item + "\n";
					}
					JOptionPane.showMessageDialog(this, str, "错误信息",
							JOptionPane.ERROR_MESSAGE);
				}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;

	// End of variables declaration//GEN-END:variables

	public static void CONTENT_PANE_PROPERTY() {
		// TODO Auto-generated method stub

	}

}