/*
 * Zzt_jf_login.java
 *
 * Created on __DATE__, __TIME__
 */

package zzt.view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import zzt.dao.Zzt_login_access;
import zzt.model.Zzt_Teacher_login;
import global.dao.Databaseconnection;
import global.dao.Teacheraccess;
import global.model.Teacher;
import global.model.View_teacher;

/**
 * 登录界面
 *    tid：
 *  	    教师编号
 * @author  zzt
 */
@SuppressWarnings("serial")
public class Zzt_jf_login extends javax.swing.JFrame {

	private String t_id;
	private String conn;
	private String t_password;
	private String con;

	/** Creates new form Zzt_jf_login */
	public Zzt_jf_login() {
		//初始化界面
		initComponents();
		//居中登录面板
		setResizable(false);
		setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		JTF_t_id = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		JPf_pssword = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6559\u5e08\u767b\u5f55");
		setBackground(new java.awt.Color(0, 0, 255));
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setForeground(new java.awt.Color(0, 0, 255));

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel1.setText("\u8d26\u53f7\uff1a");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel2.setText("\u5bc6\u7801\uff1a");

		jButton1.setText("\u767b\u5f55");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setText("\u5fd8\u8bb0\u5bc6\u7801?");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(77, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						59,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						JTF_t_id)
																				.addComponent(
																						JPf_pssword,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						186,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(74, 74,
																		74))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		66,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(52, 52,
																		52)
																.addComponent(
																		jButton2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		68,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		jLabel3)
																.addGap(38, 38,
																		38)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(46, 46, 46)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														30,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														JTF_t_id,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														JPf_pssword,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(40, 40, 40)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jButton2,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		36,
																		Short.MAX_VALUE)
																.addComponent(
																		jLabel3))
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														36,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(39, 39, 39)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//定义一个string类型的变量获取用户名的文本框
		String jtf_t_id = JTF_t_id.getText();
		//定义一个string类型的变量获取密码的密码框
		String jpf_password = new String(JPf_pssword.getPassword());
		//实例化数据库类
		try {
			//创建数据库连接
			Connection con = Databaseconnection.getconnection();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//定义一个int类型的re变量用来记录进入数据库之后登陆的状态
		int re;
		//调用Zzt_login_access类的T_login方法，把执行的结果集赋给变量re
		re = Zzt_login_access.T_login(con, jtf_t_id, jpf_password);
		if (re == 1) {
			//实例化Zzt_Teacher_login类的构造函数
			ArrayList<View_teacher> use = Teacheraccess.getview_teachertwo(jtf_t_id);
			View_teacher user = use.get(0);
		    new Zzt_if_main(user).setVisible(true);
			//登录成功之后则进入主界面，关闭当前的面板
			this.dispose();
		}
		if (re == -1) {
			//提示信息：登录失败，用户名不存在！
			JOptionPane.showMessageDialog(null, "登录失败，用户名不存在!");
			//让JIF_t_id文本框获得焦点
			JTF_t_id.requestFocus();
			//选中JIF_t_id文本框的所有内容
			JTF_t_id.selectAll();
		}
		if (re == 2) {
			//提示信息：登录失败，密码不存在！
			JOptionPane.showMessageDialog(null, "登录失败，密码不存在!");
			//让JPF_pssword文本框获得焦点
			JPf_pssword.requestFocus();
			//选中JPF_pssword文本框的所有内容
			JPf_pssword.selectAll();
		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Zzt_jf_login().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JPasswordField JPf_pssword;
	private javax.swing.JTextField JTF_t_id;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	// End of variables declaration//GEN-END:variables

}