/*
 * Zzt_JIF_teachingplan.java
 *
 * Created on __DATE__, __TIME__
 */

package zzt.view;

import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import zxx.dao.PrintObjectExcel;
import zxx.dao.TeachingAddtable;
import zxx.dao.TestFileChooserUI;

import czy.model.Tools;

import global.dao.Databaseconnection;
import global.dao.Fileselection;
import global.dao.Teacheraccess;
import global.dao.Teachingplanaccess;
import global.model.Department;
import global.model.Fillcombobox;
import global.model.Major;
import global.model.Office;
import global.model.Teachingplan;
import global.model.View_teacher;
import global.model.View_teachingplan;

/**
 *教师管理界面
 *		  vt：
 *			View_teachingplan对象
 * @author  zzt
 */
public class Zzt_JIF_teachingplan extends javax.swing.JInternalFrame {

	private static final String String = null;
	private View_teacher vt;
	private String m_id;
	private String d_id;
	private String o_id;

	/** Creates new form Zzt_JIF_teachingplan */
	public Zzt_JIF_teachingplan() {
		//初始化界面
		initComponents();
	}

	public Zzt_JIF_teachingplan(View_teacher vt) {
		//初始化界面
		initComponents();
		// 将传递的参数（登录用户的视图信息）传递给类的对应属性字段
		this.vt = vt;
		// 调用类的静态函数初始化部门下拉列表
		Fillcombobox.filldepartment(jComboBox1);
		// 调用类的静态函数初始化科室下拉列表
		Fillcombobox.filloffice(o_id, jComboBox2);
		// 调用类的静态函数初始化专业下拉列表
		Fillcombobox.fillmajor(m_id, jComboBox3);
	}

	/**
	 * 构造界面
	 * 
	 * @author zzt
	 * @param vt
	 *            ：登录用户的视图信息
	 */
	public void fillteachingplan() {
		// 取得表格的model信息
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);
		// 取得专业下拉列表选择内容
		Major mj = (Major) jComboBox3.getSelectedItem();
		// 如果为空，则退出
		if (mj == null)
			return;
		// 取得部门下拉列表选择内容
		Department dm = (Department) jComboBox1.getSelectedItem();
		// 如果为空，则退出
		if (dm == null)
			return;
		// 取得科室下拉列表选择内容
		Office of = (Office) jComboBox2.getSelectedItem();
		// 如果为空，则退出
		if (of == null)
			return;

		ArrayList<View_teachingplan> alist = Teachingplanaccess
				.getTeachingplan(mj.getM_id());
		if (alist.size() == 0)
			return;
		// 取出对应字段信息
		for (int i = 0; i < alist.size(); i++) {
			String d_name = alist.get(i).getD_name();
			String o_name = alist.get(i).getO_name();
			String m_name = alist.get(i).getM_name();
			String tp_id = alist.get(i).getTp_id();
			String tp_name = alist.get(i).getTp_name();
			String tp_mark = alist.get(i).getTp_mark();
			// 生成向量类型变量
			Vector v = new Vector();
			// 将取得数据添加到向量中
			v.add(d_name);
			v.add(o_name);
			v.add(m_name);
			v.add(tp_id);
			v.add(tp_name);
			v.add(tp_mark);
			// 将向量添加到表格中
			dtm.addRow(v);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jPanel1 = new javax.swing.JPanel();
jLabel1 = new javax.swing.JLabel();
jTextField1 = new javax.swing.JTextField();
jLabel2 = new javax.swing.JLabel();
jTextField2 = new javax.swing.JTextField();
jLabel3 = new javax.swing.JLabel();
jScrollPane2 = new javax.swing.JScrollPane();
jTextArea1 = new javax.swing.JTextArea();
jLabel4 = new javax.swing.JLabel();
jLabel5 = new javax.swing.JLabel();
jComboBox1 = new javax.swing.JComboBox();
jLabel6 = new javax.swing.JLabel();
jComboBox2 = new javax.swing.JComboBox();
jComboBox3 = new javax.swing.JComboBox();
jScrollPane1 = new javax.swing.JScrollPane();
jTable1 = new javax.swing.JTable();
jButton1 = new javax.swing.JButton();
jButton2 = new javax.swing.JButton();
jButton3 = new javax.swing.JButton();
jButton4 = new javax.swing.JButton();
jButton5 = new javax.swing.JButton();
jButton6 = new javax.swing.JButton();
jButton7 = new javax.swing.JButton();
jButton8 = new javax.swing.JButton();

setClosable(true);
setIconifiable(true);
setMaximizable(true);
setTitle("\u6559\u5b66\u65b9\u6848\u7ba1\u7406");

jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "\u6559\u5b66\u65b9\u6848\u7ba1\u7406"));

jLabel1.setText("\u6559\u5b66\u8ba1\u5212ID\uff1a");

jLabel2.setText("\u6559\u5b66\u8ba1\u5212\u540d\u79f0\uff1a");


jLabel3.setText("\u4e13\u4e1a\u540d\u79f0\uff1a");

jTextArea1.setColumns(20);
jTextArea1.setRows(5);
jScrollPane2.setViewportView(jTextArea1);

jLabel4.setText("\u5907\u6ce8\uff1a");

jLabel5.setText("\u90e8\u95e8\u540d\u79f0\uff1a");

jComboBox1.addItemListener(new java.awt.event.ItemListener() {
public void itemStateChanged(java.awt.event.ItemEvent evt) {
jComboBox1ItemStateChanged(evt);
}
});

jLabel6.setText("\u79d1\u5ba4\u540d\u79f0\uff1a");

jComboBox2.addItemListener(new java.awt.event.ItemListener() {
public void itemStateChanged(java.awt.event.ItemEvent evt) {
jComboBox2ItemStateChanged(evt);
}
});

jComboBox3.addItemListener(new java.awt.event.ItemListener() {
public void itemStateChanged(java.awt.event.ItemEvent evt) {
jComboBox3ItemStateChanged(evt);
}
});

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
jPanel1.setLayout(jPanel1Layout);
jPanel1Layout.setHorizontalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(42, 42, 42)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel1)
.addComponent(jLabel5)
.addComponent(jLabel4))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGap(7, 7, 7)
.addComponent(jLabel6)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
.addComponent(jLabel3)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGroup(jPanel1Layout.createSequentialGroup()
.addComponent(jLabel2)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jTextField2))))
.addComponent(jScrollPane2))
.addContainerGap(60, Short.MAX_VALUE))
);
jPanel1Layout.setVerticalGroup(
jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(jPanel1Layout.createSequentialGroup()
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(jLabel3)
.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel6)
.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(16, 16, 16)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel1)
.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(18, 18, 18)
.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel4)
.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(15, 15, 15))
);

jTable1.setModel(new javax.swing.table.DefaultTableModel(
	new Object [][] {
		
	},
	new String [] {
		"部门名称", "科室名称", "专业名称", "教学计划ID", "教学计划名称", "备注"
	}
) {
	boolean[] canEdit = new boolean [] {
		false, false, false, false, false, false
	};

	public boolean isCellEditable(int rowIndex, int columnIndex) {
		return canEdit [columnIndex];
	}
});
jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
public void mouseClicked(java.awt.event.MouseEvent evt) {
jTable1MouseClicked(evt);
}
});
jScrollPane1.setViewportView(jTable1);

jButton1.setText("\u6dfb\u52a0");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

jButton2.setText("\u4fee\u6539");
jButton2.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton2ActionPerformed(evt);
}
});

jButton3.setText("\u5220\u9664");
jButton3.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton3ActionPerformed(evt);
}
});

jButton4.setText("\u9000\u51fa");
jButton4.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton4ActionPerformed(evt);
}
});

jButton5.setText("\u67e5\u627e");


jButton6.setText("\u6570\u636e\u5bfc\u5165");
jButton6.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton6ActionPerformed(evt);
}
});

jButton7.setText("\u5bfc\u51fa\u89c6\u56fe\u683c\u5f0f");
jButton7.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton7ActionPerformed(evt);
}
});

jButton8.setText("\u5bfc\u51fa\u6570\u636e\u8f93\u5165\u683c\u5f0f");

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(28, 28, 28)))
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(10, 10, 10)
.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE))
.addGroup(layout.createSequentialGroup()
.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(45, 45, 45)))))
.addContainerGap())
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGap(2, 2, 2)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(17, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// TODO add your handling code here:
		//调用导出方法把文件的路径存放在tabletwo变量里
		File Filename = Fileselection.exportselect();
		File filenametow = new File(Filename + ".xls");
		String filetable = filenametow.toString();
		String tp_id = null;
		//实例化部门列表，把部门信息存放在calist变量中
		List<Teachingplan> caList = Teachingplanaccess.getteachingplan(tp_id);
		//设置excel表头信息
		String[] header = { "教学方案编号", "教学方案名称", "专业编号", "教学方案备注" };
		if (Filename == null) {
			return;
		}
		//怎么拿到导出之后的文件名
		if (filenametow.exists()) {
			System.out.println(filenametow.exists());
			int overwriteSelect = JOptionPane.showConfirmDialog(this,
					"<html><font size=3>文件" + filenametow.getName()
							+ "已存在，是否覆盖?</font><html>", "是否覆盖?",
					JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
			System.out.println(overwriteSelect);
			if (overwriteSelect == JOptionPane.YES_OPTION) {

				List<String> aList = PrintObjectExcel.printExcel(caList,
						filetable, header);
				if (aList.size() == 0) {
					JOptionPane.showMessageDialog(this, "导出成功", "提示信息",
							JOptionPane.INFORMATION_MESSAGE);
				} else {
					String str = "";
					for (String item : aList) {
						str += item + "\n";
					}
					JOptionPane.showMessageDialog(this, str, "错误信息",
							JOptionPane.ERROR_MESSAGE);
				}
			} else {
				return;
			}
		}
		List<String> aList = PrintObjectExcel.printExcel(caList, filetable,
				header);
		if (aList.size() == 0) {
			JOptionPane.showMessageDialog(this, "导出成功", "提示信息",
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			String str = "";
			for (String item : aList) {
				str += item + "\n";
			}
			JOptionPane.showMessageDialog(this, str, "错误信息",
					JOptionPane.ERROR_MESSAGE);
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// TestFileChooserUI fdialog = new TestFileChooserUI();
		JFileChooser fDialog = new JFileChooser();
		// TestFileChooserUI.getLabelForInChooser(fDialog,
		// "FileChooser.fileNameLabelText");
		String table = TestFileChooserUI.main(String);
		// TestFileChooserUI.getLabelForInChooser(fDialog, "123");
		// 初始化ExcelFileFilter文件类型过滤类
		// ExcelFileFilter excelFilter = new ExcelFileFilter();
		// // 设置文本框类型
		// fDialog.addChoosableFileFilter(excelFilter);
		// // 设置文件选择框的标题
		// fDialog.setFileFilter(excelFilter);
		// 浏览文件
		fDialog.setDialogTitle("请选择文件");
		// 弹出选择框
		// int returnVal = fDialog.showOpenDialog(null);
		// 定义table变量用来存储要浏览文件的路径
		// String table = fDialog.getSelectedFile().toString();
		// System.out.println(table);
		// 初始化department_List数组,把判定的错误信息放在department_List数组列表里
		List<String> department_List = TeachingAddtable
				.getDepartmentThrow(table);
		// System.out.println(department_List);
		// 判断department_List的错误信息个数,如果为空则导入成功,刷新页面
		if (department_List.size() == 0 || department_List == null) {
			JOptionPane.showMessageDialog(this, "导入成功", "提示信息",
					JOptionPane.INFORMATION_MESSAGE);
			fillteachingplan();

		} else {
			// 首先定义一个字符串变量为str
			String str = "";
			// 遍历数组列表错误信息
			for (String item : department_List) {
				// 把遍历过的错误信息,存放到str变量当中
				str += item + "\n";
			}
			// 提示信息：把错误信息输出到前台页面当中！
			// JOptionPane.showMessageDialog(this, str, "提示信息",
			// JOptionPane.ERROR_MESSAGE);
			//Zzt_JIF_major mj = new Zzt_JIF_major();
			// mj.setVisible(true);
			throw_ok th = new throw_ok(null, true);
			th.infomation(str);
			th.setVisible(true);

		}

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// 记录jtble1表格当前的行
		int i = jTable1.getSelectedRow();
		// 如果i==-1，说明没有选中行
		if (i == -1) {
			// 提示信息：请选中要修改的记录
			JOptionPane.showMessageDialog(this, "请选中要修改的记录", "提示信息",
					JOptionPane.INFORMATION_MESSAGE);
			return;
		}
		// 如果教学计划id文本框中没有输入内容
		if (jTextField1.getText().equals("")) {
			// 提示信息:请输入教学计划id
			JOptionPane.showMessageDialog(this, "请输入教学计划id！", "提示信息",
					JOptionPane.INFORMATION_MESSAGE);
			jTextField2.requestFocus();
			return;
		}
		if (jTextField2.getText().equals("")) {
			// 提示信息:请输入教学计划名称
			JOptionPane.showMessageDialog(this, "请输入教学计划名称！", "提示信息",
					JOptionPane.INFORMATION_MESSAGE);
			jTextField2.requestFocus();
			return;
		}

		// 定义一个变量来存放表格的第i行第0列的字符串
		Office jcbox2 = (Office) jComboBox2.getSelectedItem();
		Department jcbox1 = (Department) jComboBox1.getSelectedItem();
		Major jcbox3 = (Major) jComboBox3.getSelectedItem();
		String zzt_oid = jcbox2.getO_id();
		String zzt_did = jcbox1.getD_id();
		String zzt_mid = jcbox3.getM_id();
		String tp_id = (String) jTable1.getValueAt(i, 3);
		// 定义一个变量来存放表格的第i行第1列的字符串
		String tp_name = (String) jTable1.getValueAt(i, 4);
		// 定义一个d_id_zzt变量用来得到教学计划id文本框的内容
		String tp_mark = (String) jTable1.getValueAt(i, 5);
		String tp_id_zzt = jTextField1.getText();
		// 定义一个d_name_zzt用来得到教学计划名称文本框的内容
		String tp_name_zzt = jTextField2.getText();
		String tp_mark_zzt = jTextArea1.getText();
		// 声明数据库为空
		Connection con = null;
		try {
			// 创建数据库连接
			con = Databaseconnection.getconnection();
			// 设置数据库的自动提交方式为false
			con.setAutoCommit(false);
			// 如果当前的文本框的内容和选中的对应的列的值不匹配的时,说明用户要修改信息！
			if (!(tp_id_zzt.equals(tp_id))) {
				// 访问数据库查询教学计划编号字段值,如果当前数据库对应的字段里面的值等于用户当前已经输入的值的情况下
				if (Teachingplanaccess.findid(con, tp_id_zzt)) {
					// 提示信息：教学计划编号已经存在
					JOptionPane.showMessageDialog(this, "教学计划编号已经存在请重新输入",
							"错误信息", JOptionPane.ERROR_MESSAGE);
					// jTextField1文本框获得焦点
					jTextField1.requestFocus();
					// jtexfField1文本框全选
					jTextField1.selectAll();
					return;
				}
			}
			if (!(tp_name_zzt.equals(tp_name))) {
				if (Teacheraccess.findname(con, tp_name_zzt)) {
					// 提示信息：教学计划名称已经存在
					JOptionPane.showMessageDialog(this, "教学计划名称已经存在请重新输入",
							"错误信息", JOptionPane.ERROR_MESSAGE);
					// jTextField1文本框获得焦点
					jTextField2.requestFocus();
					// jtexfField1文本框全选
					jTextField2.selectAll();
					return;
				}
			}
			// 判定当前的输入的教学计划id和教学计划名称与数据库里面的是否重复,如果重复则提示信息
			if ((tp_id_zzt.equals(tp_id)) && (tp_name_zzt.equals(tp_name))
					&& (tp_mark_zzt.equals(tp_mark))) {
				// 提示信息:请输入您要修改的信息！
				JOptionPane.showMessageDialog(this, "请输入您要修改的信息！", "提示信息",
						JOptionPane.INFORMATION_MESSAGE);
				return;
			}
			// 定义一个变量r用来存储update方法返回的结果集
			int r = Teachingplanaccess.update(con, tp_id,
					new Teachingplan(tp_id_zzt, jTextField2.getText(), zzt_mid,
							jTextArea1.getText()));
			// 如果结果集大于0的话
			if (r > 0) {
				// 提示信息修改成功
				JOptionPane.showMessageDialog(this, "修改成功", "提示信息",
						JOptionPane.INFORMATION_MESSAGE);
				jTextField1.setText("");
				jTextField2.setText("");
				jTextArea1.setText("");
				// 开启数据库手动提交方式
				con.commit();
				// 调用fillteachingplan方法进行实时刷新表格
				fillteachingplan();
			} else {
				// 否则提示信息：修改失败请联系管理员
				JOptionPane.showMessageDialog(this, "修改失败请联系管理员", "提示信息",
						JOptionPane.ERROR_MESSAGE);
			}
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			try {
				// 如果数据库访问异常,则回滚
				con.rollback();
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			e.printStackTrace();
		}

	}

	/**
	 * 删除教师管理信息
	 * 
	 * @author zzt
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//记录表格当前的行数
		int i = jTable1.getSelectedRow();
		jTable1.setRowSelectionAllowed(true);
		String zztString = "";
		String zzt = "";
		//如果i==-1，说明没有选中行
		if (i == -1) {
			//提示信息：请选中要修改的记录
			JOptionPane.showMessageDialog(this, "请选中要删除的记录", "提示信息",
					JOptionPane.INFORMATION_MESSAGE);
			return;
		} else {
			//定义一个数组变量row存放当前选中的所有行
			int[] row = jTable1.getSelectedRows();
			//定义一个count用来存放行数
			int count = row.length;
			//遍历行数
			for (int a = 0; a < count; a++) {
				//定义一个变量来存放教学计划的第row[a]行第0列
				String t_id = (String) jTable1.getValueAt(row[a], 3);
				//定义一个空字符串变量st
				String st = ",";
				//用来存放满足删除多条语句要求的sql语句
				zzt = "(" + (zztString += "'" + t_id + "'" + (st)) + ")";
				//如果sql语句的最后一个字符是“)”则删除最后两位字符在加上一个“)”
				if (zzt.endsWith(")")) {
					zzt = zzt.substring(0, zzt.length() - 2) + ")";
				}
			}
			//提示信息,确认要删除当前记录嘛？,如果确定，则删除当前选中的记录
			int r = JOptionPane.showConfirmDialog(this, "确认要删除当前记录嘛？", "确认信息",
					JOptionPane.OK_CANCEL_OPTION);
			if (r == 0) {
				Connection con = null;
				try {
					//创建数据库连接
					con = Databaseconnection.getconnection();
					//设置数据库连接的自动提交为(false)
					con.setAutoCommit(false);
					//定义一个整型变量re来存放结果集
					int re;
					//用re来记录删除教学计划编号的方法的结果集
					re = Teachingplanaccess.Delete(con, zzt);
					//如果结果集  > 0 则删除成功
					if (re > 0) {
						JOptionPane.showMessageDialog(this, "删除记录成功！", "确认信息",
								JOptionPane.INFORMATION_MESSAGE);
						//开启数据库的手动提交
						con.commit();
						//实时刷新jtble1表格数据
						fillteachingplan();
						jTextField1.setText("");
						jTextField2.setText("");
						jTextArea1.setText("");
					} else {
						JOptionPane.showMessageDialog(this,
								"删除失败，请联系管理员进行相关操作！", "错误信息",
								JOptionPane.ERROR_MESSAGE);
					}

				} catch (ClassNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					//捕获错误异常情况进行处理,定义一个str变量,用来存放访问sql语句错误的状态值
					String str = "23000";
					//如果当前访问的状态值等于str,则提示相应信息
					if (e.getSQLState().equals(str)) {
						JOptionPane.showMessageDialog(this,
								"由于此编号有外键约束影响,暂时不能删除！", "提示信息",
								JOptionPane.INFORMATION_MESSAGE);
					}
				}
			}
		}

	}

	/**
	 * 添加教师管理信息
	 * 
	 * @author zzt
	 */

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		//得到教学计划id的文本框
		String tp_id = jTextField1.getText();
		//得到教学计划名称的文本框
		String tp_name = jTextField2.getText();
		//得到教学计划备注的文本框
		String tp_mark = jTextArea1.getText();
		//得到专业下拉列表的内容
		Major jcbox3 = (Major) jComboBox3.getSelectedItem();
		String m_id = jcbox3.getM_id();
		// 如果教学计划id文本框内容为空
		if (tp_id.equals("")) {
			// 提示信息：教学计划id不能为空！
			JOptionPane.showMessageDialog(this, "教学计划id不能为空！");
			jTextField2.requestFocus();
			return;
		}
		// 如果教学计划id文本框内容为空
		if (tp_name.equals("")) {
			// 提示信息：部门名称不能为空！
			JOptionPane.showMessageDialog(this, "方案计划名称不能为空！");
			jTextField2.requestFocus();
			return;
		}
		Connection con = null;
		try {
			// 创建数据库连接
			con = Databaseconnection.getconnection();
			// 实例化教学计划的构造方法
			Teachingplan tp = new Teachingplan(tp_id, tp_name, m_id, tp_mark);
			// 设置数据库的自动提交方式为false
			con.setAutoCommit(false);
			// 访问数据库查询教学计划编号字段值,如果当前数据库对应的字段里面的值等于用户当前已经输入的值的情况下
			if (Teachingplanaccess.findid(con, tp_id)) {
				// 提示信息：类型编号已经存在
				JOptionPane.showMessageDialog(this, "教学计划id已经存在请重新输入", "错误信息",
						JOptionPane.ERROR_MESSAGE);
				// jTextField1文本框获得焦点
				jTextField1.requestFocus();
				// jtexfField1文本框全选
				jTextField1.selectAll();
				return;
			}
			// 访问数据库查询教学计划名称字段值,如果当前数据库对应的字段里面的值等于用户当前已经输入的值的情况下
			if (Teachingplanaccess.findname(con, tp_name)) {
				// 提示信息：类型名称已经存在
				JOptionPane.showMessageDialog(this, "教学计划名称已经存在请重新输入", "错误信息",
						JOptionPane.ERROR_MESSAGE);
				// jTextField1文本框获得焦点
				jTextField2.requestFocus();
				// jtexfField1文本框全选
				jTextField2.selectAll();
				return;
			}
			// 定义r变量存放结果集
			int r = Teachingplanaccess.insert(con, tp);
			// 如果r>=1
			if (r >= 1) {
				// 则提示信息：添加成功！
				JOptionPane.showMessageDialog(this, "添加成功！");
				// 开始数据库的手动提交方式
				con.commit();
				//调用fillteachingplan方法刷新表格内容
				fillteachingplan();
				//清空教学计划id的文本框
				jTextField1.setText("");
				//清空教学计划名称的文本框
				jTextField2.setText("");
				//清空教学计划备注的文本框
				jTextArea1.setText("");
			}
			// 如果记录集1则提示信息教学计划编号插入失败，请联系系统管理员！
			if (r < 1) {
				Tools.connectionroolback(con, "教师编号插入失败，请联系系统管理员！");
				return;
			}
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
		} finally {
			try {
				//如果插入异常则回滚
				con.rollback();
				if (!con.isClosed())
					con.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	//通过教学计划名称来显示表格内容
	private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {
		fillteachingplan();
	}

	//点击科室名称下拉列表将信息传递到专业列表当中
	private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {
		// TODO add your handling code here:
		//得到科室下拉列表的内容
		Office of = (Office) jComboBox2.getSelectedItem();
		//如果为空则返回
		if (of == null)
			return;
		String o_id = of.getO_id();
		//调用静态方法通过教学计划编号得到当前专业名称
		Fillcombobox.fillmajor(o_id, jComboBox3);
	}

	//将表格中的每列数据传输到对应的文本框中
	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		//获取jtable1的表格的当前行
		int row = jTable1.getSelectedRow();
		//把第row行的第三列的内容赋值到教学计划id的文本框当中
		jTextField1.setText((String) jTable1.getValueAt(row, 3));
		//把第row行的第三列的内容赋值到教学计划名称的文本框当中
		jTextField2.setText((String) jTable1.getValueAt(row, 4));
		//把第row行的第三列的内容赋值到教学计划备注的文本框当中
		jTextArea1.setText((String) jTable1.getValueAt(row, 5));
	}

	//点击部门名称下拉列表将信息传递到科室列表当中
	private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {
		// TODO add your handling code here:
		//得到部门下拉列表的内容
		Department dm = (Department) jComboBox1.getSelectedItem();
		//如果为空则返回
		if (dm == null)
			return;
		String d_id = dm.getD_id();
		//调用静态方法通过部门编号得到当前专业名称
		Fillcombobox.filloffice(d_id, jComboBox2);
		//设置专业下拉列表为空
		jComboBox3.setSelectedItem(null);
	}

	//关闭当前教学计划管理面板
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here	
		this.dispose();
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}