/*
 * Zzt_JIF_Changepassword.java
 *
 * Created on __DATE__, __TIME__
 */

package zzt.view;

import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import global.dao.Databaseconnection;
import global.dao.Teacheraccess;
import global.model.View_teacher;

/**
 *
 * @author  zzt
 */
public class Zzt_JIF_Changepassword extends javax.swing.JInternalFrame {

	/** Creates new form Zzt_JIF_Changepassword */
	private View_teacher teacher;
	public Zzt_JIF_Changepassword() {
		initComponents();
	}

	public Zzt_JIF_Changepassword(View_teacher u) {
		initComponents();
		teacher = u;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jPasswordField3 = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setTitle("\u4fee\u6539\u5bc6\u7801");

		jLabel2.setText("\u539f\u5bc6\u7801\uff1a");

		jLabel3.setText("\u65b0\u5bc6\u7801\uff1a");

		jLabel4.setText("\u786e\u8ba4\u5bc6\u7801\uff1a");

		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d6\u6d88");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(36,
																				36,
																				36)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jLabel2)
																										.addComponent(
																												jLabel3))
																						.addComponent(
																								jLabel4))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jPasswordField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								240,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPasswordField2)
																						.addComponent(
																								jPasswordField3)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(84,
																				84,
																				84)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(78,
																				78,
																				78)
																		.addComponent(
																				jButton2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				90,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(48, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(32, 32, 32)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(42, 42, 42)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jPasswordField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(54, 54, 54)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jPasswordField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												43, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																42,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																42,
																Short.MAX_VALUE))
										.addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addGap(40, 40, 40)
								.addComponent(jLabel1)
								.addContainerGap(374, Short.MAX_VALUE))
				.addComponent(jPanel1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel1)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String fp = new String(jPasswordField1.getPassword());
		String np = new String(jPasswordField2.getPassword());
		String ap = new String(jPasswordField3.getPassword());

		if (fp.equals("")) {
			JOptionPane.showMessageDialog(this, "原密码不能为空", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField1.requestFocus();
			return;
		}
		if (np.equals("")) {
			JOptionPane.showMessageDialog(this, "新密码不能为空", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField2.requestFocus();
			return;
		}
		if (ap.equals("")) {
			JOptionPane.showMessageDialog(this, "确认密码不能为空", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField3.requestFocus();
			return;
		}

		if (!np.equals(ap)) {
			JOptionPane.showMessageDialog(this, "新密码与确认密码不相同，请重新输入", "错误信息",
					JOptionPane.ERROR_MESSAGE);
			jPasswordField3.requestFocus();
			jPasswordField3.selectAll();
			return;
		}
		
		Connection con = null;
		try {
			con = Databaseconnection.getconnection();
			// 创建数据库连接
//			System.out.println(teacher.getT_password());
			if (!fp.equals(teacher.getT_password())) {
				JOptionPane.showMessageDialog(this, "原密码错误", "错误信息",
						JOptionPane.ERROR_MESSAGE);
				jPasswordField1.requestFocus();
				jPasswordField1.selectAll();
				return;
			} 
				// 设置数据库的自动提交方式为false
				// con.setAutoCommit(false);
//			System.out.println(teacher.getT_id());
			teacher.setT_password(np);
				int re = Teacheraccess.changepassword(con, teacher);
				if (re > 0) {
					JOptionPane.showMessageDialog(this, "您已成功修改您的密码！", "提示信息",
							JOptionPane.INFORMATION_MESSAGE);
					jPasswordField1.setText("");
					jPasswordField2.setText("");
					jPasswordField3.setText("");
				} else {
					JOptionPane.showMessageDialog(this, "请您联系管理员！", "错误信息",
							JOptionPane.ERROR_MESSAGE);
				}
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JPasswordField jPasswordField3;
	// End of variables declaration//GEN-END:variables

}