/*
 * Zzt_JIF_Schoolyear.java
 *
 * Created on __DATE__, __TIME__
 */

package zzt.view;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import czy.model.Tools;

import global.dao.Databaseconnection;
import global.dao.Departmentaccess;
import global.dao.Schoolyearaccess;
import global.model.Department;
import global.model.Schoolyear;

/**
 *
 * @author  __USER__
 */
public class Zzt_JIF_Schoolyear extends javax.swing.JInternalFrame {

	private Schoolyear sy;
	private int sy_id;
	private String sy_name;

	/** Creates new form Zzt_JIF_Schoolyear */
	public Zzt_JIF_Schoolyear() {
//		initComponents();
	}

	public Zzt_JIF_Schoolyear(Schoolyear sy) {
//		initComponents();
		this.sy = sy;
//		schoolyeartable();
		//		setColumnWidth();
	}

	//	public void schoolyeartable() {
	//		//首先给d_id变量设为空值
	//		int sy_id = 0;
	//		//声明DefaultTableModel 得到jtble1表格上的模型
	//		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
	//		//设置表格的行数从0开始计数
	//		dtm.setRowCount(0);
	//		//初始化ArrayList列表，通过d_id主键查询department（部门表）
	//		ArrayList<Schoolyear> aList = Schoolyearaccess.getSchoolyear(sy_id);
	//		// 遍历部门的数组列表
	//		for (int i = 0; i < aList.size(); i++) {
	//			// 取出对应字段信息
	//			sy_id = aList.get(i).getSy_id();
	//			String sy_name = aList.get(i).getSy_name();
	//			// 生成向量类型变量
	//			Vector v = new Vector();
	//			// 将取得数据添加到向量中
	//			v.add(sy_id);
	//			v.add(sy_name);
	//			// 将向量添加到表格中
	//			dtm.addRow(v);
	//		}
	//	}
	//
	//	/** This method is called from within the constructor to
	//	 * initialize the form.
	//	 * WARNING: Do NOT modify this code. The content of this method is
	//	 * always regenerated by the Form Editor.
	//	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();

		setTitle("\u5b66\u671f\u7ba1\u7406");

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(
				javax.swing.BorderFactory.createLineBorder(new java.awt.Color(
						0, 0, 0)), "\u5b66\u671f\u7ba1\u7406"));

		jLabel1.setText("\u5b66\u671f\u7f16\u53f7\uff1a");

		jLabel2.setText("\u5b66\u671f\u540d\u79f0\uff1a");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(26, 26, 26)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												138,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												187,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(26, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(22, Short.MAX_VALUE)));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "学期编号", "学期名称" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
		});
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u6dfb\u52a0");

		jButton2.setText("\u5220\u9664");

		jButton3.setText("\u4fee\u6539");

		jButton4.setText("\u9000\u51fa");

		jButton5.setText("\u5bfc\u5165");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 567,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jButton1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										73,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										71,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jButton4,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										75,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(118, 118, 118)
								.addComponent(jButton5,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										96, Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										175,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		40,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						38,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButton2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						38,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jButton3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						38,
																						Short.MAX_VALUE)
																				.addComponent(
																						jButton4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						37,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(27, 27,
																		27))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jButton5,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		37,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(28, 28,
																		28)))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	//
	//	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
	//		// TODO add your handling code here:
	//		this.dispose();
	//	}
	//
	//	private void setColumnWidth() {
	//		TableColumn Column;
	//		// 设置教学任务表格各列宽度
	//		Column = jTable1.getColumnModel().getColumn(0);
	//		Column.setPreferredWidth(50);
	//		Column = jTable1.getColumnModel().getColumn(1);
	//		Column.setPreferredWidth(250);
	//	}
	//
	//	private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
	//		// TODO add your handling code here:
	//		int i = jTable1.getSelectedRow();
	//		jTextField1.setText(jTable1.getValueAt(i, 0).toString());
	//		jTextField2.setText((String) jTable1.getValueAt(i, 1));
	//	}
	//
	//	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	//		// TODO add your handling code here:
	//		// TODO add your handling code here:
	//		// String d_id_zzt = "01";
	//		// int d_id_int = Integer.parseInt(d_id_zzt) + 1;
	//		// String d_str = "0" + Integer.toString(d_id_int);
	//		// //得到当前jTextField2文本框
	//		String d_id_zzt = jTextField1.getText();
	//		String d_name_zzt = jTextField2.getText();
	//		// try {
	//		// ResultSet acc = Departmentaccess.findmax(conn);
	//		// } catch (SQLException e1) {
	//		// // TODO Auto-generated catch block
	//		// e1.printStackTrace();
	//		// }
	//		// 如果当前的文本框内容为空
	//		if (d_id_zzt.equals("")) {
	//			// 提示信息：部门编号不能为空！
	//			JOptionPane.showMessageDialog(this, "学期编号不能为空！");
	//			jTextField1.requestFocus();
	//			return;
	//		}
	//		// 如果部门名称文本框内容为空
	//		if (d_name_zzt.equals("")) {
	//			// 提示信息：部门名称不能为空！
	//			JOptionPane.showMessageDialog(this, "学期名称不能为空！");
	//			jTextField2.requestFocus();
	//			return;
	//		}
	//		// 实例化Department类
	//		Schoolyear sy = new Schoolyear(sy_id, sy_name);
	//		Connection con = null;
	//		try {
	//			// 创建数据库连接
	//			con = Databaseconnection.getconnection();
	//			// 设置数据库的自动提交方式为false
	//			con.setAutoCommit(false);
	//			// 访问数据库查询部门编号字段值,如果当前数据库对应的字段里面的值等于用户当前已经输入的值的情况下
	//			if (Schoolyearaccess.findid(con, d_id_zzt)) {
	//				// 提示信息：类型编号已经存在
	//				JOptionPane.showMessageDialog(this, "学期编号已经存在请重新输入", "错误信息",
	//						JOptionPane.ERROR_MESSAGE);
	//				// jTextField1文本框获得焦点
	//				jTextField1.requestFocus();
	//				// jtexfField1文本框全选
	//				jTextField1.selectAll();
	//				return;
	//			}
	//			// 访问数据库查询d_name字段值,如果当前数据库对应的d_name字段里面的值等于用户当前已经输入的值的情况下
	//			if (Schoolyearaccess.findname(con, d_name_zzt)) {
	//				// 提示信息：类型名称已经存在
	//				JOptionPane.showMessageDialog(this, "学期名称已经存在请重新输入", "错误信息",
	//						JOptionPane.ERROR_MESSAGE);
	//				// jTextField1文本框获得焦点
	//				jTextField2.requestFocus();
	//				// jtexfField1文本框全选
	//				jTextField2.selectAll();
	//				return;
	//			}
	//			// 定义r变量存放结果集
	//			int r = Schoolyearaccess.insert(con, sy);
	//			// 如果r>=1
	//			if (r >= 1) {
	//				// 则提示信息：添加成功！
	//				JOptionPane.showMessageDialog(this, "添加成功！");
	//				// 开始数据库的手动提交方式
	//				con.commit();
	//				schoolyeartable();
	//				jTextField1.setText("");
	//				jTextField2.setText("");
	//			}
	//			// 如果r<1
	//			if (r < 1) {
	//				// 则提示信息部门编号插入失败，请联系系统管理员！
	//				Tools.connectionroolback(con, "编号插入失败，请联系系统管理员！");
	//				return;
	//			}
	//		} catch (ClassNotFoundException e) {
	//			// TODO Auto-generated catch block
	//			e.printStackTrace();
	//		} catch (SQLException e) {
	//		} finally {
	//			try {
	//				con.rollback();
	//				if (!con.isClosed())
	//					con.close();
	//			} catch (SQLException e) {
	//				// TODO Auto-generated catch block
	//				e.printStackTrace();
	//			}
	//		}
	//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}